In [2]:
import tensorflow as tf

In [3]:
#mathematical operations
x= tf.constant([1,2,3])
y=tf.constant([4,5,6])

z=tf.add(x,y)
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

In [7]:
a= tf.random.normal((2,3))
b= tf.random.normal((3,7))

c=tf.matmul(a,b)  #matrix multiplication
c


<tf.Tensor: shape=(2, 7), dtype=float32, numpy=
array([[-2.3502426 , -0.69406044,  1.4125707 , -1.3966256 ,  0.2392641 ,
        -1.6905328 ,  0.8623907 ],
       [-0.6968303 ,  0.21130657, -0.10999371,  0.39399672, -1.0330265 ,
        -0.5261445 ,  0.0191263 ]], dtype=float32)>