In [1]:
import tensorflow as tf

In [3]:
#initialization of tensor

x = tf.constant(4, shape=(1,1))
x

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[4]], dtype=int32)>

In [5]:
y= tf.constant([[1,2,3],[4,5,6]])
y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [12]:
z=tf.ones((3,4))
z

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [11]:
a= tf.zeros((2,3))
a

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [15]:
b=tf.eye(2)
b

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>