In [2]:
import numpy as np


In [4]:
list=np.array([1,2,3,4])
a=list.sort
print(a)


<built-in method sort of numpy.ndarray object at 0x00000181CDF9B210>


In [6]:
np.arange(40)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [7]:
np.arange(2,10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [8]:
np.arange(10)





array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(1, 10, 12)

array([ 1.        ,  1.81818182,  2.63636364,  3.45454545,  4.27272727,
        5.09090909,  5.90909091,  6.72727273,  7.54545455,  8.36363636,
        9.18181818, 10.        ])

In [14]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [19]:
np.diag([1,2,3], 2)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 0, 0, 0, 3],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [2]:
a=np.array(([1,2], [3,4]))
np.diag(a)

NameError: name 'np' is not defined

In [3]:
import numpy as np


In [5]:

np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,0])

np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [15]:
x=np.array([[1,3], [2,4]])
y=np.array([[5,6]])

np.concatenate((x,y), axis=0)

array([[1, 3],
       [2, 4],
       [5, 6]])

In [21]:
a= np.array([[1,2,3], [4,5,6]])
a.shape

(2, 3)

In [27]:
a=np.array([1,2,3,4,5,6])
print(a)

[1 2 3 4 5 6]


In [31]:
b=a.reshape(2,3)
print(b)

[[1 2 3]
 [4 5 6]]


In [37]:
list=np.array([1,2,3,4])
list[-2:]

array([3, 4])

In [39]:
b= np.array([[1,2,3], [4,5,6]])
print(a[a%2==0])

[2 4 6]


In [42]:
b=np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [44]:
b.sum(axis=1)

array([ 6, 15])

In [45]:
b*3.2

array([[ 3.2,  6.4,  9.6],
       [12.8, 16. , 19.2]])

In [48]:
b.max()
b.min()


1

In [58]:
cars=["bmw", "volvo", "honda"]

for z in cars:
    print(z)
    if z == "volvo":
     break

bmw
volvo


In [60]:
for x in range(5,50, 5):
    print(x)

5
10
15
20
25
30
35
40
45


In [61]:
cars=["bmw", "volvo", "honda"]
fruits=["apple", "banana", "straw"]

for x in cars:
    for y in fruits:
        print(x,y)

bmw apple
bmw banana
bmw straw
volvo apple
volvo banana
volvo straw
honda apple
honda banana
honda straw


In [62]:
adj = ["red", "big", "tasty"]
fruits = ["apple", "banana", "cherry"]

for x in adj:
  for y in fruits:
    print(x, y)

red apple
red banana
red cherry
big apple
big banana
big cherry
tasty apple
tasty banana
tasty cherry


In [ ]:
for x in [1,2,3]:
    pass

In [9]:
dict={x: x*2 for x in [2,4,6,8,10]}
print(dict)



{2: 4, 4: 8, 6: 12, 8: 16, 10: 20}


In [13]:
def msg():
    print("congratulations")

msg()

congratulations


In [17]:
def add(x,y=3):
      """Function to add the values given in function parameter"""
    z=x+y
    return z


add(3)

6

In [29]:
def msg1():
  x= "I love music"

  def msg2():
    print(x)



msg1()


In [5]:
import numpy as np
import pandas as pd

In [12]:
dict= { 'Name':['prijal', 'aayush', 'arogya','ram', 'shyam', 'nikesh', 'abhi', 'bibek', 'harry'],
        'Rollno.':[21,22,24,32,45,67,54,87,98],
        'Birthday':[4, 23, 18, 90, 70, 63, 43, 57, 96]  }

x= pd.DataFrame(dict)
print(x)

     Name  Rollno.  Birthday
0  prijal       21         4
1  aayush       22        23
2  arogya       24        18
3     ram       32        90
4   shyam       45        70
5  nikesh       67        63
6    abhi       54        43
7   bibek       87        57
8   harry       98        96


In [8]:
x.to_csv('data.csv')

PermissionError: [Errno 13] Permission denied: 'data.csv'

In [16]:
x.head(3)
x.tail(5)
x.describe()

,Rollno.,Birthday
count,9.000000,9.000000
mean,50.000000,51.555556
std,28.783676,32.074566
min,21.000000,4.000000
25%,24.000000,23.000000
50%,45.000000,57.000000
75%,67.000000,70.000000
max,98.000000,96.000000


In [22]:
x['Birthday'][4]=99

C:\Users\khadk\AppData\Local\Temp\ipykernel_8296\383514537.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['Birthday'][4]=99


In [23]:
x['Birthday'][4]

99

In [28]:
dates = pd.date_range("20130101", periods=8)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06', '2013-01-07', '2013-01-08'],
              dtype='datetime64[ns]', freq='D')

In [31]:
y=pd.DataFrame(np.random.randn(8,6), index=dates, columns=list("ABCDEF"))
y

,A,B,C,D,E,F
2013-01-01,-0.025636,0.785060,0.295292,1.677696,1.266196,-0.394959
2013-01-02,0.004529,1.486447,-0.040493,0.626036,0.650468,0.600319
2013-01-03,0.678678,0.691701,0.836575,0.639781,-0.953332,-1.924981
2013-01-04,-1.170596,-0.082560,-0.285305,-0.843026,-1.039101,1.167353
2013-01-05,-1.488448,-1.094755,1.296797,0.820360,0.302428,1.198568
2013-01-06,-0.958742,1.154621,-0.621628,-0.822775,0.069798,-0.871052
2013-01-07,-1.161069,-0.828872,0.018188,0.517868,1.365511,-0.696885
2013-01-08,1.230064,-0.438646,-0.388917,1.753169,0.651630,-1.551908


In [2]:
import numpy as np
import pandas as pd



In [6]:
x=pd.Series(np.random.rand(6))
x

0    0.728484
1    0.391413
2    0.957756
3    0.957191
4    0.932428
5    0.841680
dtype: float64

In [14]:
y=pd.DataFrame(np.random.randn(10, 5), index=np.arange(10))
y

,0,1,2,3,4
0,-0.279860,-1.422845,1.151669,1.046857,0.243139
1,-0.444672,-0.977063,-0.053019,0.600524,0.000579
2,0.021284,0.779890,0.312251,-0.467888,1.846882
3,0.053535,-0.615338,0.252312,-0.543458,0.741481
4,0.559826,-0.533134,0.420558,1.566041,1.700601
5,-0.496036,-0.465608,-2.474941,0.943129,0.826131
6,-0.894072,-0.115004,-0.213664,-0.797584,0.530278
7,-1.016297,2.107951,1.949161,0.773890,1.917995
8,0.805595,0.010107,-0.703877,0.573464,-0.400990
9,-0.629807,0.187535,-0.935993,2.405604,-0.687913


In [1]:
import numpy as np
import pandas as pd

In [3]:
dict2={
    'name':['prijal', 'kushal', 'biyash', 'pranil'],
    'marks':[99, 92, 88, 84],
    'city':['kathmandu', 'lalitpur', 'bhaktapur', 'Nuwakot']
}

In [5]:
x=pd.DataFrame(dict2)
x

,name,marks,city
0,prijal,99,kathmandu
1,kushal,92,lalitpur
2,biyash,88,bhaktapur
3,pranil,84,Nuwakot


In [7]:
x.to_csv('marks_no_index.csv', index=False)

In [8]:
x.head(1)

,name,marks,city
0,prijal,99,kathmandu


In [9]:
x.describe()

,marks
count,4.000000
mean,90.750000
std,6.396614
min,84.000000
25%,87.000000
50%,90.000000
75%,93.750000
max,99.000000
